spring:
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.203.100:3306/seckill
    hikari:
      pool-name: DateHikariCP
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 3000
  #      redis配置
  redis:
    host: 192.168.203.100
    lettuce:
      pool:
        #        最大连接数默认8
        max-active: 8
#        最大等待时间
        max-wait: 10000ms
#        最大空闲连接 -最小空闲连接
        max-idle: 8
  rabbitmq:
    host: localhost
    listener:
      simple:
#        消费者最小数量
        concurrency: 10
#        消费者最大数量
        max-concurrency: 10
#        限制消费者每次只能处理一条消息，处理完在处理下一条消息
        prefetch: 1
#        是否自动启动容器
        auto-startup: true
#        被拒绝时是否重新进入队列
        default-requeue-rejected: true
    template:
      retry:
#        发布重试
        enabled: true
#        重试时间，默认1000ms
        initial-interval: 1000ms
#        重试最大次数，默认3
        max-attempts: 3
#        最大重试时间 默认10000ms
        max-interval: 10000ms
#        重试乘数 比如 2.0 第一次10s，第二次就20s ,3--40s
        multiplier: 1
  web:
    resources:
      static-locations: classpath:/static/


mybatis-plus:

  mapper-locations: classpath*:/mapper/*Mapper.xml

  type-aliases-package: com.maomao.seckill.pojo

logging:
  level:
    com.maomao.seckill.mapper: debug




